/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UTSPemrograman2;

import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class Laundry_Paymentt extends javax.swing.JFrame {

    /**
     * Creates new form Laundry_Paymentt
     */
    public Laundry_Paymentt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Jenis_Cuci = new javax.swing.JComboBox<>();
        Harga = new javax.swing.JTextField();
        Berat = new javax.swing.JTextField();
        Total_Harga = new javax.swing.JTextField();
        Bayar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jTextField3.setText("jTextField3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(51, 255, 153));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Laundry Paymentt");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 160, 50));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Jenis Cuci");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 110, 20));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 20, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Harga Per Kilo ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 120, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Berat");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 90, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Total Harga");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Bayar");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 90, 30));

        Jenis_Cuci.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Jenis", "Cuci Basah", "Cuci Kering", "Cuci Setrika" }));
        Jenis_Cuci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jenis_CuciActionPerformed(evt);
            }
        });
        jPanel1.add(Jenis_Cuci, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 190, 40));
        jPanel1.add(Harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 190, 40));

        Berat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                BeratKeyReleased(evt);
            }
        });
        jPanel1.add(Berat, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 190, 40));

        Total_Harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Total_HargaActionPerformed(evt);
            }
        });
        jPanel1.add(Total_Harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 190, 40));
        jPanel1.add(Bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 190, 40));

        jButton1.setText("Transaksi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 110, 50));

        jButton2.setText("Batal");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 110, 50));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 450, 515);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Total_HargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Total_HargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Total_HargaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Jenis_Cuci.setSelectedItem("pilih");
        Harga.setText("");
        Berat.setText("");
        Total_Harga.setText("");
        Bayar.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Jenis_CuciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jenis_CuciActionPerformed
        if (Jenis_Cuci.getSelectedItem().toString().equalsIgnoreCase("Cuci Basah")){
            Harga.setText("5000");
        }else if (Jenis_Cuci.getSelectedItem().toString().equalsIgnoreCase("Cuci Kering")){
            Harga.setText("4000");
            }else if (Jenis_Cuci.getSelectedItem().toString().equalsIgnoreCase("Cuci Setrika")){
            Harga.setText("6000");
            }     
    }//GEN-LAST:event_Jenis_CuciActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int bayar = Integer.parseInt(Bayar.getText());
int ttl_hrga = Integer.parseInt(Total_Harga.getText());
int kembalian = bayar - ttl_hrga; // Perbaiki logika, bayar - total harga

// Konversi kembalian ke String untuk ditampilkan
String kembali = Integer.toString(kembalian);
System.out.println("Kembalian Anda: " + kembali);

// Reset form setelah perhitungan
Jenis_Cuci.setSelectedItem("pilih");
Harga.setText("");
Berat.setText("");
Total_Harga.setText("");
Bayar.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BeratKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BeratKeyReleased
        int harga = Integer.parseInt(Harga.getText());
        int berat = Integer.parseInt(Berat.getText());
        double totalbyr = harga * berat;
        String Total = Double.toString(totalbyr);
        Total_Harga.setText(Total); 
    }//GEN-LAST:event_BeratKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Laundry_Paymentt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Laundry_Paymentt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Laundry_Paymentt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Laundry_Paymentt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Laundry_Paymentt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Bayar;
    private javax.swing.JTextField Berat;
    private javax.swing.JTextField Harga;
    private javax.swing.JComboBox<String> Jenis_Cuci;
    private javax.swing.JTextField Total_Harga;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
